#!/usr/bin/env node
// =============================================================================
// Brand token stylesheet generator.
//
// Composes a plain-CSS token file (the public API a product serves, e.g. at
// /brand.css) from the package's roles.css and the product's brand file.
// Commit the output; never edit it by hand.
//
//   ds-build-brand-css --brand src/system/brands/birthguide.css \
//                      --out public/brand.css \
//                      --name BirthGuide --url https://birthguide.com.au
//   ds-build-brand-css ... --check      exit 1 when the output is stale
//
// Published: the roles' aliasing semantics, the brand's values in both
// modes, and the mode-constant type, spacing and radius tokens re-homed
// onto :root so they resolve without Tailwind. Not published: the
// --color-*/--shadow-* @theme aliases (Tailwind utility mappings) and the
// brand's font mapping (a framework variable; document the family in the
// brand file instead).
// =============================================================================

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import path from 'node:path'

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`)
  return i === -1 ? undefined : process.argv[i + 1]
}
const brandPath = arg('brand')
const outPath = arg('out')
const name = arg('name') ?? 'Brand'
const url = arg('url') ?? ''
const check = process.argv.includes('--check')
if (!brandPath || !outPath) {
  console.error(
    'usage: ds-build-brand-css --brand <brand.css> --out <path> [--name <Name>] [--url <site>] [--check]',
  )
  process.exit(2)
}

const ROLES = path.resolve(import.meta.dirname, '../../css/roles.css')
const roles = readFileSync(ROLES, 'utf8')
const brand = readFileSync(path.resolve(brandPath), 'utf8')

function block(source: string, file: string, re: RegExp, label: string): string {
  const m = source.match(re)
  if (!m) {
    throw new Error(
      `brand.css generator: the ${label} block was not found in ${file}. ` +
        'Its shape changed; update the generator to match.',
    )
  }
  return m[1]
}

const LIGHT = /^:root,\n\.force-light \{\n([\s\S]*?)\n\}/m
const DARK = /^\.dark \{\n([\s\S]*?)\n\}/m
const THEME = /^@theme inline \{\n([\s\S]*?)\n\}/m

const rolesLight = block(roles, 'roles.css', LIGHT, ':root/.force-light')
const rolesDark = block(roles, 'roles.css', DARK, '.dark')
const rolesTheme = block(roles, 'roles.css', THEME, '@theme inline')
const brandLight = block(brand, brandPath, LIGHT, ':root/.force-light')
const brandDark = block(brand, brandPath, DARK, '.dark')

const modeConstantTokens = rolesTheme
  .split('\n')
  .filter((line) => /^\s*--(?:text|spacing|radius)-[\w-]+:/.test(line))
  .join('\n')
if (!modeConstantTokens.includes('--text-display')) {
  throw new Error('brand.css generator: no --text-* tokens matched in the roles @theme block.')
}

const contract = block(
  roles,
  'roles.css',
  /(brand-contract:theme[\s\S]*?)\n\s*brand-contract:end/,
  'brand contract',
)
  .split('\n')
  .map((l) => l.replace(/^\s{3}/, ''))
  .join('\n')

const header = `/* =============================================================================
   ${name} brand tokens${url ? `\n   ${url.replace(/\/$/, '')}/brand.css` : ''}

   GENERATED by @fracazo/design-system (ds-build-brand-css) from the
   package's roles.css and this product's brand file. Never edit by hand:
   edit the brand file and rebuild.

   Two tiers: primitives hold literals (--brand, --band, --ink); semantics
   reference them via var() (--primary, --border). Light values live on
   :root, dark overrides on .dark; set the .dark class on <html> from
   prefers-color-scheme before first paint, or mirror the .dark block inside
   a prefers-color-scheme media query. .force-light pins a subtree to light
   regardless of mode, e.g. document previews that represent printed paper.

   Skinning: the roles block below is shared by every product on this
   system; a brand supplies every property in the contract with its own
   values, light and dark. The roles stay identical; only the values change.

   ${contract.split('\n').join('\n   ')}
   ============================================================================= */
`

const output = `${header}
/* ── Roles: the aliasing semantics, shared by every brand ──────────────── */
:root,
.force-light {
${rolesLight}
}

.dark {
${rolesDark}
}

/* ── Brand: ${name} values ────────────────────────────────────────────── */
:root,
.force-light {
${brandLight}
}

.dark {
${brandDark}
}

/* ── Type, band rhythm and radius (mode-constant; consumed as Tailwind
   theme tokens inside the app, plain custom properties out here) ──────── */
:root {
${modeConstantTokens}
}
`

const out = path.resolve(outPath)
if (check) {
  const current = existsSync(out) ? readFileSync(out, 'utf8') : null
  if (current !== output) {
    console.error(`${outPath} is stale against the brand file. Rebuild it and commit the result.`)
    process.exit(1)
  }
  console.log(`${outPath} is current.`)
} else {
  writeFileSync(out, output)
  console.log(`written: ${out}`)
}
